# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpander3', '0002_url_address_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_address',
            name='full_url',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AlterField(
            model_name='url_address',
            name='http_status',
            field=models.IntegerField(default=404),
        ),
        migrations.AlterField(
            model_name='url_address',
            name='page_title',
            field=models.TextField(default='none'),
        ),
    ]
