# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-01 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpander3', '0003_auto_20160818_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_address',
            name='city',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='url_address',
            name='country',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='url_address',
            name='created_date',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='url_address',
            name='domain_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='url_address',
            name='email',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='url_address',
            name='expires_date',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='url_address',
            name='fax',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='url_address',
            name='name',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='url_address',
            name='organization',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='url_address',
            name='postal_code',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='url_address',
            name='state',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='url_address',
            name='street1',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='url_address',
            name='telephone',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='url_address',
            name='updated_date',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='url_address',
            name='full_url',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AlterField(
            model_name='url_address',
            name='http_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url_address',
            name='image',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AlterField(
            model_name='url_address',
            name='page_title',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='url_address',
            name='timestamp',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='url_address',
            name='wayback_url',
            field=models.CharField(default='N/A', max_length=300),
        ),
    ]
